### ISSUE TITLE
deb package breaks dependencies

### ISSUE THREAD

**Issue by killua-eu** [kamax-matrix/mxisd#112] opened 2019-01-26 22:09 UTC
Hi, running `dpkg -i v1.3.0-alpha.2` without having java installed first results in this:

```
root@c3:~# dpkg -i ./mxisd_1.3.0-alpha.2_all.deb 
Selecting previously unselected package mxisd.
(Reading database ... 39745 files and directories currently installed.)
Preparing to unpack ./mxisd_1.3.0-alpha.2_all.deb ...
Unpacking mxisd (1.3.0-alpha.2) ...
dpkg: dependency problems prevent configuration of mxisd:
 mxisd depends on openjdk-8-jre | openjdk-8-jre-headless | openjdk-8-jdk | openjdk-8-jdk-headless; however:
  Package openjdk-8-jre is not installed.
  Package openjdk-8-jre-headless is not installed.
  Package openjdk-8-jdk is not installed.
  Package openjdk-8-jdk-headless is not installed.

dpkg: error processing package mxisd (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mxisd```

Manually installing 

```root@c3:~# apt install openjdk-8-jre-headless
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 openjdk-8-jre-headless : Depends: ca-certificates-java but it is not going to be installed
                          Depends: java-common (>= 0.28) but it is not going to be installed
                          Depends: libcups2 but it is not going to be installed
                          Depends: liblcms2-2 (>= 2.2+git20110628) but it is not going to be installed
                          Depends: libjpeg8 (>= 8c) but it is not going to be installed
                          Depends: libfontconfig1 but it is not going to be installed
                          Depends: libnss3 (>= 2:3.17.1) but it is not going to be installed
                          Depends: libpcsclite1 (>= 1.3.0) but it is not going to be installed
                          Depends: libxi6 but it is not going to be installed
                          Depends: libxrender1 but it is not going to be installed
                          Depends: libxtst6 but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

which requires some unneeded corrections. Its just a minor inconvenience, but I guess one that you guys should know about. (I got this result on a 18.04 ubuntu container while testing the 1.3 version for inclusion in an ansible role)

**Comment by maxidorius** [comment] 2019-01-27 21:43
This problem seems to reflect previous issue(s) with package installs, not directly related to mxisd.
Can you reproduce this on a fresh 18.04 Ubuntu install?

**Comment by maxidorius** [comment] 2019-02-04 01:15
@killua-eu Any update? Else I'll close the issue.

**Comment by maxidorius** [comment] 2019-02-06 02:17
Closing due to inactivity from OP. Please re-open if needed.

**Closed by maxidorius** 2019-02-06 02:17 UTC
Labels: support
